run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G104 # gosec ignores unused errors

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

formatting:
  gofmt: -s
  goimports: -s
