FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY server/go.mod ./
RUN go mod download

COPY server/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine:3.19

RUN apk --no-cache add ca-certificates busybox-extras

EXPOSE 6379 8080

COPY --from=builder /app/server .

CMD ["./server"]
