FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY tests/go.mod ./
COPY tests/bench.go ./
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o bench bench.go

FROM alpine:3.19

RUN apk --no-cache add ca-certificates busybox-extras

WORKDIR /app

COPY --from=builder /app/bench .

CMD ["./bench", "mini-kv-server", "6379", "10000", "10"]
